# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: nodeless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:GetObject"
      - "s3:PutObject"
    Resource:
      - "arn:aws:s3:::*"

functions:
  optimize:
    handler: handler.handle
    environment:
      bucket: vagnernodeserverless
    events:
      - s3:
          bucket: vagnernodeserverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: vagnernodeserverless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
